services:

  influxdb:
    image: influxdb:2.4-alpine
    container_name: influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb2
    entrypoint: [ "./entrypoint.sh" ]
    networks:
      smartgym-network:
        ipv4_address: 172.30.0.114

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: ${MQTT_BROKER}
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      smartgym-network:
        ipv4_address: 172.30.0.111
    restart: always

  sensor-simulation:
    build:
      context: ./sensor-simulation
    container_name: sensor_simulation
    env_file:
      - .env
    depends_on:
      - mqtt
    networks:
      smartgym-network:
        ipv4_address: 172.30.0.112

  node-red:
    build:
      context: ./node-red
    container_name: node_red
    env_file:
      - .env
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    depends_on:
      - mqtt
    networks:
      smartgym-network:
        ipv4_address: 172.30.0.110
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME}
      - GF_PATHS_PROVISIONING=${GF_PATHS_PROVISIONING}
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      smartgym-network:
        ipv4_address: 172.30.0.115

networks:
  smartgym-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16